name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::590183809276:role/RepoBackupStack-GitHubActionsRole4F1BBA26-VJ98fpJ4Z0cI
          role-session-name: GitHub-to-AWS-via-FederatedOIDC
          aws-region: us-east-1

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: poc-github-backup
          aws_region: us-east-1

name: Sync Github with CodeCommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  sync:
    name: sync
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Create some environment variables
        run: |
          echo "CODECOMMIT_URL=https://git-codecommit.us-east-1.amazonaws.com/v1/repos/poc-github-backup" >> $GITHUB_ENV
          echo "REPO_URL=https://github.com/thiagolinkeen/repo-backup.git" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.
      
      
      - run: git branch -a

      - run: git tag -l

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.CODECOMMIT_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - run: git config --global --add safe.directory /github/workspace

      - run: git config --global credential.'https://git-codecommit.*.amazonaws.com'.helper '!aws codecommit credential-helper $@'
      - run: git config --global credential.UseHttpPath true

      - run: git remote add sync $CODECOMMIT_URL

      - run: git push --tags --force --prune sync "refs/remotes/origin/*:refs/heads/*"
              